### ISSUE TITLE
User request: convert between grams and moles

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/concentration#28]
Reported via PhEThelp by Alexander

Hello,
I love your simulators and use them for chemistry lessons all the time, they’re great!
 
I think it would be even better if the concentration simulators could convert between grams and moles so students can practice calculations between molarity and percent by mass.  The solvent and solute controls are also somewhat clumsy (shaking crystals from a saltshaker or pouring concentrate/water in with a dropper or faucet) and it would be better if they could be manipulated with greater precision.
 
Just a few thoughts from a chemistry educator.  Keep up the great work!

**Comment by pixelzoom** [comment]
The only units shown in this simulation are "mol/L", via the Concentration meter. So I'm not very clear on what the user is asking for here.  Does this issue perhaps pertain to some other sim? (Molarity?) The user refers to "the concentration simulators", so it's unclear.

@ariel-phet This is a new feature request, usually assigned to the lead designer. In this case, the lead designer is no longer with the project. Who will be making the call on whether to design and implement this feature?

**Comment by ariel-phet** [comment]
This feature request is beyond the learning goals of this particular sim. Closing.
