### ISSUE TITLE
User request: add one solution to another

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/concentration#33]
User suggestion emailed to PhEThelp:
"I want to ask:  why a solution can't be added to another different solution in the simulation that is mentioned in the title. Moreover, in my opinion I think it should be added so students can create questions out of the process and try to challenge themselves with something that is a bit more complicated. Thank you "

**Comment by pixelzoom** [comment]
Probably best to assign this to one of the chemists to respond. But my understanding is that supporting this would require an entirely different (more complicated) model.

**Comment by ycarpenterphet** [comment]
@oliver-phet Would you like me to write a response to the user?

**Comment by pixelzoom** [comment]
@ycarpenterphet I'm assuming that @oliver-phet does want you to write a response. You'll need to ask him for contact info, since we don't post that info public GitHub issues.  If you post your reply here, reminder to strip out names and email addresses.

**Comment by oliver-phet** [comment]
If you feel it is worth it to write back, I can send along contact info. I thank all users when they make a request for a feature in a sim and tell them we will consider it, so there is no need to write back if we won't be pursuing.

**Comment by pixelzoom** [comment]
@ycarpenterphet Whether you reply or not... Could you briefly summarize the pedagogical reason, for posterity? This is not the first time that this feature has been proposed, and it would be nice to be able to refer to this issue in the future for an answer. Thanks!

**Comment by pixelzoom** [comment]
@ycarpenterphet what is the status on this?

**Comment by pixelzoom** [comment]
@ycarpenterphet Could you briefly summarize your response to the customer, then close this issue?

**Comment by pixelzoom** [comment]
Never got a summary from @ycarpenterphet.   But the decision was made not to do this.  Closing.
