### ISSUE TITLE
branch: together

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/concentration#37]
I believe that this branch contains a version of Concentration that is instrumented with together (data collection) support, and that the only difference between master should be the .html file.  @samreid please correct me or elaborate.

**Comment by samreid** [comment]
That is correct.

**Comment by jbphet** [comment]
I believe that this branch can now be removed.  The HTML file is now in the together repo for running in RequireJS mode, and the build tools now support creation of a built version.  The handling of the version identifiers still needs some work, but that's another story.

**Comment by jbphet** [comment]
I went ahead and removed the branch.  Closing.
