### ISSUE TITLE
[together.js] save/load the state of the shaker particles

### ISSUE THREAD

**Issue by samreid** [phetsims/concentration#41]
Currently the positions of the shaker particles are not being saved/loaded.  They were still animated in mirror.html by running the concentration model clock and observing motion of the shaker.  However, running the model clock in sims is not a good solution in general, and it has been disabled.  So we need a way to transmit the shaker particle states.  This should also solve a bug where reset all creates a single solute particle (when the shaker goes back to its initial location).

**Comment by samreid** [comment]
I made pretty good progress on the problem above--good enough to work for save/load and record/playback.  It is still missing some details like the velocity of the particles and their orientation, though.

**Comment by samreid** [comment]
@jbphet anything else needed here?

**Comment by pixelzoom** [comment]
@jbphet is this done?

**Comment by jbphet** [comment]
I started taking a look at this yesterday and noticed a few issues, which @pixelzoom appears also to have noticed, since he logged https://github.com/phetsims/beers-law-lab/issues/102.  So I think that this needs a bit more attention.

**Comment by pixelzoom** [comment]
Add https://github.com/phetsims/beers-law-lab/issues/103 and https://github.com/phetsims/beers-law-lab/issues/104 to the list of related issues, they also deal with deficiencies in support for particles.

**Comment by samreid** [comment]
@pixelzoom how much of this issue is critical for S2015R and how much can wait until we can dedicate some more time to together?

**Comment by pixelzoom** [comment]
I think we can punt on this for S2015R. Unlabeling.

**Comment by pixelzoom** [comment]
Back to @samreid.  If you don't plan on working on this, feel free to unassign.

**Comment by samreid** [comment]
No plans to work on this at the moment.

**Comment by ariel-phet** [comment]
Assigning back to @jbphet (since it was originally his issue) now that S2015R has been removed

**Comment by samreid** [comment]
The remaining work is detailed in https://github.com/phetsims/beers-law-lab/issues/103, closing.
