### ISSUE TITLE
Remaining 1.2.0 redeploy items 

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/concentration#46]
- [x] Rosetta test (Opening sim to trusted translators for beta)
- [x] Check teacher tips are up to date
- [ ] Check sim primer is up to date

**Comment by ariel-phet** [comment]
wow, already translated!

**Comment by pixelzoom** [comment]
wow indeed. that's both impressive and scary.

**Comment by ariel-phet** [comment]
Why scary?

**Comment by pixelzoom** [comment]
scary that someone is watching what we're doing that closely, and is that responsive.

**Comment by pixelzoom** [comment]
the good kind of scary. like the good kind of bad :)

**Comment by ariel-phet** [comment]
The primer projects are being covered by https://github.com/phetsims/tasks/issues/429 and https://github.com/phetsims/tasks/issues/430 closing
