### ISSUE TITLE
Added Features

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/concentration#47]
We are looking to add the following features to increase flexibility for lab use and for younger grade level. I suggest making all of these as behaviors that are designed into master and part of our published sim, and accessible through query parameters. 

- [ ] Add a readout display for the Solute added (in g)
- [ ] Display concentration units in percent (as is option in Beaker). 
- [ ] Display volume tick mark labels in mL (that is 500 mL and 1000 mL)

Assigning to @ariel-phet to discuss with @pixelzoom

**Comment by pixelzoom** [comment]
@kathy-phet @ariel-phet 

(1) Do you want to add these features only to the Concentration sim, or should they also appear in the "Concentration" screen of Beer's Law Lab.  If the latter, then I'm going to move this issue to repository beers-law-lab, since that's where the work will be done.  And I will probably break this into 3 issues, one for each feature, since the requested features are independent.

(2) Do you have any specification for how you'd like these features to appear in the sim? Eg, associated controls, labels, placement.

**Comment by pixelzoom** [comment]
(3) Are there any deadlines for these features?

**Comment by ariel-phet** [comment]
1) Considering the relationship between BLL and concentration, would it be easier to have this implemented in BLL? I think we will want to do whatever you feel is the best in terms of maintenance costs.

2) I figure we would discuss this (for the percent and the mL these would replace the current labels when the query parameter was activated)...so these would not be additional labels, they would be replacement. For the Solute display, I have some thoughts, but you and I should discuss, and then probably get some opinions from Amy H.

3) Yes - ideally complete next week. This would be top priority, with the understanding that it is bumping function builder priority for next week. I think we could hand a link that is tested, but not yet published on the website.

When would be a good time to chat? Text me if you want to chat soon. Monday/this weekend is pretty open as well.

**Comment by pixelzoom** [comment]
Excluding these features from Beer's Law Lab would be problematic and add cost.  The Concentration sim (and repo) gets *all* of its implementation from the Beer's Law Lab sim (and repo).

Available to chat Monday for sure, hit me up during core hours. Will let you know if anything opens up this weekend.

**Comment by ariel-phet** [comment]
@pixelzoom sounds good, feel free to break this up into 3 separate issues in BLL and close this issue.

**Comment by pixelzoom** [comment]
This issues has been moved to 3 issues (one for each requested feature) in beers-law-lab.  See links to the issues directly above this comment.

Closing.
