### ISSUE TITLE
User request: add Sodium Chloride as solute

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/concentration#49]
I was wondering is there any way to put Sodium Chloride (NaCl) as a compound in the concentration simulation Phet has.  I am trying to build a desalination unit in WISE and I wanted to embed the Phet concentration simulation.  It would be fantastic if one of the compounds was NaCl so that students could consider saltwater concentrations.  Thank you.

Assigning to @ariel-phet

**Comment by ariel-phet** [comment]
@amyh-phet what do you think? Salt seems like the quintessential solute...think there is a reason we did not put it in? I am guessing part of the reason for not using salt was the color of the liquid will not change much to give a visual cue of concentration.

@pixelzoom my impression is the model is written in such a way that adding another solute to the concentration screen would not be difficult (although might be tricky on the BL screen without the spectroscopic data)?

**Comment by amyh-phet** [comment]
@ariel-phet  and @pixelzoom  While NaCl is a commonly discussed solute, I think that the clear, colorless solution that would result does not allow the user to connect solution color to concentration.   Mathematically I see no difficulty with adding NaCl to the sim, but it would not be useful in the BL screen.

**Comment by pixelzoom** [comment]
The "Concentration" and "Beer's Law" screens use different models.  So while the lists of solutes/solutions are currently the same, it is possible to add a new solute to ConcentrationModel without adding a corresponding solution to BeersLawModel.  So we could conceivably add NaCl to the "Concentration" screen only. 

Impact:
(1) NaCl will show no change in color as concentration changes, as noted above by @amyh-phet.
(2) Different combo box list between Concentration and Beer's Law screen (NaCL absent in latter).

If you want to move forward with adding NaCl, we'll need the following properties:

• common name (Salt? Table Salt?)
• formula (NaCl)
• stock concentration, in mol/L
• molar mass, in g/mol
• 3 colors (min, middle, max) used to denote solution concentration (all fully transparent?)
• color for precipitate particles (fully transparent?)

**Comment by amyh-phet** [comment]
@pixelzoom   I can get the needed information to you tomorrow.  I'd like to dig a bit to see if we need to model the solution as fully transparent across all concentrations used in the sim.

**Comment by pixelzoom** [comment]
@ariel-phet Priority? Maintenance release or minor version increment? A maintenance release will have higher development cost, but require less testing.  A minor release will have lower development cost, but will require a full RC test cycle, and triaging open issues to see what other changes will be picked up.

**Comment by ariel-phet** [comment]
Definitely a minor release.

Priority is "as time allows" - Function Builder is definitely the priority, but if you need something that is a bit less mentally taxing feel free to tackle the enhancement.

**Comment by amyh-phet** [comment]
@pixelzoom 

- Common name:  Table salt
- formula:  NaCl
- stock concentration: 5.50 mol/L
- molar mass: 58.443 g/mol
- solubility: 6.15 mol/L
- 3 colors:   

min: no color-fully transparent
middle:  no color-fully transparent
max:  Would be nice to add a bit of opacity here.   Can we try  f1f2f2 at 40% transparency?  

- color for precipitate particles:  f1f2f2 (very light gray)

Let me know if you need more info from me or if colors for solution/precipitate needs

**Comment by pixelzoom** [comment]
Reminder to self: add corresponding entry to beers-law-lab-api.js.

**Comment by pixelzoom** [comment]
Moving this issue to https://github.com/phetsims/beers-law-lab/issues/169, since this work will be done in the beers-law-lab repository.
