### ISSUE TITLE
why is there no 1.4 branch?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/concentration#51]
The current production branch is 1.3, current published version is 1.3.5.   On 11/3/2016, @samreid created branch 1.5-phetio.  @samreid why did you skip 1.4 and 1.4-phetio?

**Comment by samreid** [comment]
package.json changed to 1.4 on 5/23/2016.
It made it up to 1.4.0-phetiodev.3 on 9/26/16
On 10/4/16 there was a commit https://github.com/phetsims/concentration/commit/0076fab0239f0d4a95bda59b30e333c9033a12a6 with commit message
 
> Branched and updated version see phetsims/phet-io#662

Perhaps the developer following the "sim_deployment.md" instructions at the time probably thought a new minor version was part of the steps.

**Comment by pixelzoom** [comment]
OK. Sounds like this happened when the process and version id convention was unclear.

Closing.
