### ISSUE TITLE
Usability on small screens review

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/concentration#53]
Per @kathy-phet's request in https://github.com/phetsims/QA/issues/295 I am making issues in each published sim repo detailing the pointer areas and usability of sims on phone sized screens.  Done on an iPhone 7 iOS 12 device.

Potential Difficulties Noticed:
* In landscape mode the blue pointer area for the concentration tool looks odd

Screenshots:
![Image from iOS (1)](https://user-images.githubusercontent.com/41024075/55908851-b6687880-5b97-11e9-99df-d85830cc1d9b.png)
![Image from iOS](https://user-images.githubusercontent.com/41024075/55908852-b7010f00-5b97-11e9-95f9-9f1bda20bf0c.png)

**Comment by pixelzoom** [comment]
This sim is identical to the Concentration screen in Beer's Law Lab, so I would expect this issue to be a duplicate (subset) of https://github.com/phetsims/beers-law-lab/issues/236.

**Comment by arouinfar** [comment]
Thanks @KatieWoe.

From a design perspective, I would make the same decisions about the touch areas for Concentration and the Concentration screen of Beer's Law Lab. From what I understand about the code, it all lives in the `beers-law-lab` repo, and any change made to BLL would automatically apply to Concentration. If this is true, I think this would be safe to close @pixelzoom.

**Comment by pixelzoom** [comment]
Yep, it all lives in beers-law-lab, and anything we do there applies to concentration.  So closing as duplicate.
