### ISSUE TITLE
User suggestion: addition of temperature slider

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/concentration#60]
> I just wanted to let you know that I find your concentration simulator (Concentration 1.3.21) very useful for illustrating the concept of a saturation point for students. I was just emailing to suggest that the addition of a temperature bar would be extremely useful for illustrating how saturation changes with temperature

**Comment by pixelzoom** [comment]
Development-wise, this would be a major change/enhancement.  This simulation (and its parent sim Beer's Law Lab) has nothing related to temperature in the model or the view.  In addition to a thermometer, a heating/cooling source would presumably be needed.

**Comment by arouinfar** [comment]
I agree with @pixelzoom's assessment. This request goes well beyond the scope of the learning goals, so it is not a change I would consider.
