### ISSUE TITLE
Concentration - Publish 1.7.0 with PhET-iO upgrades

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/concentration#62]
Publishing at the same time as Beer's Law Lab 1.7, see https://github.com/phetsims/beers-law-lab/issues/300 for QA history.

**Comment by pixelzoom** [comment]
... at the same time as 
* https://github.com/phetsims/beers-law-lab/issues/300

**Comment by pixelzoom** [comment]
From the above comment:
> The concentration repo version number should be brought forward to 1.7, so that it's in sync with beers-law-lab.

Apparently no one read this, and 1.6.0-dev.2 was published.  Luckily this is not an RC, so we can still correct this before creating the release branch.

**Comment by zepumph** [comment]
We were going to do this for RC, and didn't know it mattered for dev.

**Comment by zepumph** [comment]
Version number updated above.

**Comment by matthew-blackman** [comment]
2/3/2023 1.7.0-rc.1 testing begins, brands=phet,phet-io.

beers-law-lab:

https://github.com/phetsims/qa/issues/894
https://phet-dev.colorado.edu/html/beers-law-lab/1.7.0-rc.1

concentration:

https://github.com/phetsims/qa/issues/895
https://phet-dev.colorado.edu/html/concentration/1.7.0-rc.1

**Comment by pixelzoom** [comment]
2/17/2023: 1.7.0 was published.
